;;; lean-explorer.el --- Live view of the C Lean compiles your file to -*- lexical-binding: t; -*-

;; Author: Jan Mas Rovira
;; Version: 0.1.0
;; Package-Requires: ((emacs "29.1"))
;; Keywords: languages, tools

;;; Commentary:

;; A Compiler Explorer for Lean 4: `M-x lean-explorer' in a .lean buffer opens
;; a side window with the C that `lake build <Module>:c' produces, and keeps it
;; in sync as you save (or as you type, see `lean-explorer-auto-build').  The
;; window then follows the Lean buffer you switch to, and the declaration at
;; point within it.
;;
;; Freshness is always visible: a header-line badge in the C window says
;; whether the shown C was generated from the source you are looking at, and
;; stale C is grayed out.  The source buffer's mode-line carries the same badge.
;;
;; Two backends, switched with `lean-explorer-toggle-backend': `c' shows what
;; lake already emits, `asm' runs `leanc -S' over it and shows the assembly
;; under .lake/build/lean-explorer/.
;;
;; Vibe-coded: written largely by prompting an AI coding agent.  Expect rough
;; edges; review before relying on it.
;;
;; Install (plain Emacs):
;;   (add-to-list 'load-path "/path/to/lean-explorer")
;;   (autoload 'lean-explorer "lean-explorer" nil t)
;;
;; Install (Doom, in config.el):
;;   (add-load-path! "~/projects/lean-explorer")
;;   (use-package! lean-explorer :commands (lean-explorer lean-explorer-mode))
;;   (map! :map neo-lean-mode-map :localleader "c" #'lean-explorer)
;;
;; Commands: `lean-explorer' (open/close), `lean-explorer-rebuild',
;; `lean-explorer-show-log', `lean-explorer-follow-declaration'.
;;
;; In the output buffer: g rebuilds, b switches backend, l shows the build log,
;; q closes (with evil: gr, gb, gl, q).  C-c C-c, C-c C-b and C-c C-l work in
;; either case.

;;; Code:

(require 'cl-lib)
(require 'subr-x)

(declare-function evil-normalize-keymaps "evil-core")
(defvar asm-comment-char)

(defgroup lean-explorer nil
  "Live view of the C generated by the Lean compiler."
  :group 'tools
  :prefix "lean-explorer-")

(defcustom lean-explorer-backend 'c
  "Which compiler output to show, `c' or `asm'.
Set per buffer by `lean-explorer-toggle-backend'."
  :type '(choice (const c) (const asm)))

(defcustom lean-explorer-lake-program "lake"
  "The lake executable used to build the C facet."
  :type 'string)

(defcustom lean-explorer-leanc-program "leanc"
  "The leanc executable used to assemble the generated C."
  :type 'string)

(defcustom lean-explorer-asm-flags
  '("-S" "-O3" "-fno-asynchronous-unwind-tables")
  "Flags handed to `lean-explorer-leanc-program' to produce assembly."
  :type '(repeat string))

(defcustom lean-explorer-auto-build 'save
  "When to regenerate the C.
`save'   rebuild after the source buffer is saved.
`idle'   save and rebuild after `lean-explorer-idle-delay' of inactivity.
`manual' only on `lean-explorer-rebuild'."
  :type '(choice (const save) (const idle) (const manual)))

(defcustom lean-explorer-idle-delay 1.5
  "Idle seconds before an automatic build.
Only used when `lean-explorer-auto-build' is `idle'."
  :type 'number)

(defcustom lean-explorer-build-on-open t
  "Whether opening the explorer builds when the C on disk looks stale."
  :type 'boolean)

(defcustom lean-explorer-dim-when-stale t
  "Whether to gray out C that no longer matches the source."
  :type 'boolean)

(defcustom lean-explorer-follow-buffer t
  "Whether a visible explorer window follows the Lean buffer you switch to.
With nil each Lean buffer keeps its own explorer, and the window keeps
showing the C of the buffer it was opened from."
  :type 'boolean)

(defcustom lean-explorer-follow-point t
  "Whether the C window follows the declaration at point in the source buffer."
  :type 'boolean)

(defcustom lean-explorer-follow-delay 0.4
  "Idle seconds before the C window follows point."
  :type 'number)

(defcustom lean-explorer-font-lock-max-size (* 2 1024 1024)
  "Skip font-locking C output larger than this many bytes."
  :type 'integer)

(defcustom lean-explorer-display-action
  '((display-buffer-in-side-window)
    (side . right)
    (window-width . 0.5)
    (dedicated . t))
  "`display-buffer' action used to show the C buffer."
  :type 'sexp)

(defface lean-explorer-fresh '((t :inherit success :weight bold))
  "Badge face for C that matches the source.")

(defface lean-explorer-stale '((t :inherit warning :weight bold))
  "Badge face for C that no longer matches the source.")

(defface lean-explorer-failed '((t :inherit error :weight bold))
  "Badge face for a failed build.")

(defface lean-explorer-dimmed '((t :inherit shadow))
  "Face laid over stale C output.")

;;; State.  In the source buffer:

(defvar-local lean-explorer--module nil)
(defvar-local lean-explorer--root nil)
(defvar-local lean-explorer--artifact nil "Absolute path of the file on show.")
(defvar-local lean-explorer--c-file nil "Absolute path of the generated .c.")
(defvar-local lean-explorer--view nil "The buffer showing the C.")
(defvar-local lean-explorer--proc nil)
(defvar-local lean-explorer--state 'unknown "One of unknown, fresh, stale, building, failed.")
(defvar-local lean-explorer--built-hash nil "Hash of the source that produced the shown C.")
(defvar-local lean-explorer--pending nil)
(defvar-local lean-explorer--timer nil)
(defvar-local lean-explorer--saving nil "Non-nil while we save on the way into a build.")
(defvar-local lean-explorer--declined nil "Non-nil once this buffer failed to resolve.")

;;; In the C buffer:

(defvar-local lean-explorer--source nil)
(defvar-local lean-explorer--dim nil)
(defvar-local lean-explorer--followed nil)
(defvar-local lean-explorer--font-lock-suppressed nil)

(defvar lean-explorer--follow-timer nil "Global idle timer driving `lean-explorer-follow-point'.")

(defvar lean-explorer-mode)

;;; Module resolution

(defun lean-explorer--project-root (file)
  (when-let* ((dir (locate-dominating-file
                    file
                    (lambda (d)
                      (or (file-exists-p (expand-file-name "lakefile.toml" d))
                          (file-exists-p (expand-file-name "lakefile.lean" d)))))))
    (expand-file-name dir)))

(defun lean-explorer--ir-file (root parts)
  (expand-file-name (concat (string-join parts "/") ".c")
                    (expand-file-name ".lake/build/ir/" root)))

(defun lean-explorer--src-dirs (root)
  "Directories declared as srcDir in ROOT's lakefile."
  (let (dirs)
    (dolist (name '("lakefile.toml" "lakefile.lean"))
      (let ((file (expand-file-name name root)))
        (when (file-readable-p file)
          (with-temp-buffer
            (insert-file-contents file)
            (goto-char (point-min))
            (while (re-search-forward "srcDir[ \t]*:?=[ \t]*\"\\([^\"]+\\)\"" nil t)
              (push (string-trim (match-string 1) "\\./" "/") dirs))))))
    dirs))

(defun lean-explorer--resolve (file)
  "Return (ROOT MODULE C-FILE) for FILE, or nil if it is outside a lake package."
  (when-let* ((root (lean-explorer--project-root file))
              (rel (string-remove-suffix
                    ".lean" (file-relative-name (file-truename file) (file-truename root))))
              (parts (split-string rel "/")))
    ;; a lean_lib with srcDir starts the module path below the package root, so
    ;; prefer the longest suffix lake has already emitted C for, then any
    ;; srcDir the lakefile declares
    (let* ((tails (cl-loop for i from 0 below (length parts) collect (nthcdr i parts)))
           (best (or (cl-find-if (lambda (p) (file-exists-p (lean-explorer--ir-file root p))) tails)
                     (cl-find-if (lambda (p) (member (string-join (butlast parts (length p)) "/")
                                                     (lean-explorer--src-dirs root)))
                                 (cdr tails))
                     parts)))
      (list root (string-join best ".") (lean-explorer--ir-file root best)))))

(defun lean-explorer--asm-file (root parts)
  (expand-file-name (concat (string-join parts "/") ".s")
                    (expand-file-name ".lake/build/lean-explorer/" root)))

(defun lean-explorer--set-paths ()
  "Point the C and artifact paths at the current backend's output."
  (let ((parts (split-string lean-explorer--module "\\.")))
    (setq lean-explorer--c-file (lean-explorer--ir-file lean-explorer--root parts)
          lean-explorer--artifact (if (eq lean-explorer-backend 'asm)
                                      (lean-explorer--asm-file lean-explorer--root parts)
                                    lean-explorer--c-file))))

(defun lean-explorer--hash ()
  "Hash of the source buffer's whole contents."
  (save-restriction (widen) (secure-hash 'md5 (current-buffer))))

;;; The C buffer

(defvar-keymap lean-explorer-view-mode-map
  :doc "Keymap of the buffer showing generated C."
  "g" #'lean-explorer-rebuild
  "l" #'lean-explorer-show-log
  "b" #'lean-explorer-toggle-backend
  "q" #'quit-window
  "C-c C-c" #'lean-explorer-rebuild
  "C-c C-l" #'lean-explorer-show-log
  "C-c C-b" #'lean-explorer-toggle-backend)

;; evil's normal state shadows a plain minor-mode map, so the same commands
;; need evil auxiliary bindings; `gr' leaves `gg' and friends alone
(with-eval-after-load 'evil
  (when (fboundp 'evil-define-key*)
    (evil-define-key* '(normal motion) lean-explorer-view-mode-map
      "q" #'quit-window
      "gr" #'lean-explorer-rebuild
      "gl" #'lean-explorer-show-log
      "gb" #'lean-explorer-toggle-backend))
  (add-hook 'lean-explorer-view-mode-hook #'evil-normalize-keymaps))

(define-minor-mode lean-explorer-view-mode
  "Minor mode of the buffer showing Lean's generated C."
  :lighter nil
  (when lean-explorer-view-mode
    (setq-local header-line-format '(:eval (lean-explorer--header))
                truncate-lines t
                buffer-read-only t)))

(defconst lean-explorer--labels
  '((fresh . "in sync")
    (stale . "stale")
    (building . "building…")
    (failed . "build failed")
    (unknown . "not built")))

(defun lean-explorer--face (state)
  (pcase state
    ('fresh 'lean-explorer-fresh)
    ('failed 'lean-explorer-failed)
    (_ 'lean-explorer-stale)))

(defun lean-explorer--state-of (src)
  (if (buffer-live-p src) (buffer-local-value 'lean-explorer--state src) 'unknown))

(defun lean-explorer--header ()
  (let* ((src lean-explorer--source)
         (state (lean-explorer--state-of src))
         (module (if (buffer-live-p src) (buffer-local-value 'lean-explorer--module src) "?")))
    (concat (propertize (format " %s %s "
                                (if (eq state 'fresh) "●" "○")
                                (alist-get state lean-explorer--labels))
                        'face (lean-explorer--face state))
            (propertize (format " %s" module) 'face 'mode-line-buffer-id)
            (propertize (format " · %s" (if (eq lean-explorer-backend 'asm) "asm" "C"))
                        'face 'shadow)
            (propertize (lean-explorer--hint) 'face 'shadow))))

(defun lean-explorer--hint ()
  "The key hint for the header line, following the active evil state."
  (if (memq (bound-and-true-p evil-state) '(normal motion visual operator))
      "   gr rebuild · gb backend · gl log · q close"
    "   g rebuild · b backend · l log · q close"))

(defun lean-explorer--lighter ()
  (concat " " (propertize (format "C:%s" (alist-get lean-explorer--state lean-explorer--labels))
                          'face (lean-explorer--face lean-explorer--state))))

(defun lean-explorer--ensure-view ()
  "Return the C buffer of the current source buffer, creating it if needed."
  (unless (buffer-live-p lean-explorer--view)
    (let* ((src (current-buffer))
           (name (lean-explorer--view-name lean-explorer--module lean-explorer-backend))
           (taken (get-buffer name))
           ;; a second buffer on the same module must not steal the first's view
           (buf (if (and taken (buffer-live-p (buffer-local-value 'lean-explorer--source taken)))
                    (generate-new-buffer name)
                  (get-buffer-create name))))
      (lean-explorer--configure-view buf src lean-explorer-backend)
      (setq lean-explorer--view buf)))
  lean-explorer--view)

(defun lean-explorer--view-name (module backend)
  (format "*lean-%s: %s*" (if (eq backend 'asm) "asm" "c") module))

(defun lean-explorer--configure-view (buf src backend)
  "Put BUF in BACKEND's major mode and make it the view of SRC."
  (with-current-buffer buf
    (remove-overlays)
    (lean-explorer--view-major-mode backend)
    (setq-local lean-explorer--source src
                lean-explorer-backend backend)
    (lean-explorer-view-mode 1)))

(defun lean-explorer--view-major-mode (backend)
  (ignore-errors
    (cond ((eq backend 'asm)
           (when (require 'asm-mode nil t)
             ;; the Lean toolchain emits GAS, whose comments start with `#'
             (let ((asm-comment-char ?#))
               (asm-mode))))
          ((and (fboundp 'c-ts-mode) (fboundp 'treesit-language-available-p)
                (treesit-language-available-p 'c))
           (c-ts-mode))
          (t (c-mode)))))

(defun lean-explorer--load-artifact (src)
  "Reload the generated C of SRC into its view buffer, keeping the viewport."
  (let ((buf (buffer-local-value 'lean-explorer--view src))
        (file (buffer-local-value 'lean-explorer--artifact src)))
    (when (and (buffer-live-p buf) (file-readable-p file))
      (with-current-buffer buf
        (let* ((inhibit-read-only t)
               (line (line-number-at-pos))
               (col (current-column))
               (win (get-buffer-window buf t))
               (top (and win (line-number-at-pos (window-start win)))))
          (erase-buffer)
          (insert-file-contents file)
          (set-buffer-modified-p nil)
          (cond ((> (buffer-size) lean-explorer-font-lock-max-size)
                 (when font-lock-mode
                   (setq lean-explorer--font-lock-suppressed t)
                   (font-lock-mode -1)))
                (lean-explorer--font-lock-suppressed
                 (setq lean-explorer--font-lock-suppressed nil)
                 (font-lock-mode 1)))
          (goto-char (point-min))
          (forward-line (1- line))
          (move-to-column col)
          (when top
            (save-excursion
              (goto-char (point-min))
              (forward-line (1- top))
              (set-window-start win (point))))
          (setq lean-explorer--followed nil))))))

;;; Freshness

(defun lean-explorer--set-state (state)
  (setq lean-explorer--state state)
  (force-mode-line-update)
  (when (buffer-live-p lean-explorer--view)
    (with-current-buffer lean-explorer--view
      (lean-explorer--apply-dim state)
      (force-mode-line-update))))

(defun lean-explorer--apply-dim (state)
  "Gray the C buffer out while it does not match its source."
  (if (not (and lean-explorer-dim-when-stale (memq state '(stale building failed))))
      (when (overlayp lean-explorer--dim)
        (delete-overlay lean-explorer--dim)
        (setq lean-explorer--dim nil))
    (unless (overlayp lean-explorer--dim)
      (setq lean-explorer--dim (make-overlay (point-min) (point-max) nil nil t))
      (overlay-put lean-explorer--dim 'face 'lean-explorer-dimmed)
      (overlay-put lean-explorer--dim 'priority 100))
    (move-overlay lean-explorer--dim (point-min) (point-max))))

(defun lean-explorer--refresh-state ()
  "Recompute freshness by comparing the buffer against what was last compiled."
  (unless (or (process-live-p lean-explorer--proc) (eq lean-explorer--state 'failed))
    (lean-explorer--set-state
     (cond ((null lean-explorer--built-hash)
            (if (file-readable-p lean-explorer--artifact) 'stale 'unknown))
           ((equal lean-explorer--built-hash (lean-explorer--hash)) 'fresh)
           (t 'stale)))))

(defun lean-explorer--after-change (&rest _)
  (when (timerp lean-explorer--timer) (cancel-timer lean-explorer--timer))
  (let ((src (current-buffer)))
    (setq lean-explorer--timer
          (run-with-idle-timer
           (if (eq lean-explorer-auto-build 'idle) lean-explorer-idle-delay 0.2) nil
           (lambda ()
             (when (buffer-live-p src)
               (with-current-buffer src
                 (when lean-explorer-mode
                   (lean-explorer--refresh-state)
                   (when (and (eq lean-explorer-auto-build 'idle)
                              (memq lean-explorer--state '(stale unknown failed)))
                     (lean-explorer--build))))))))))

(defun lean-explorer--after-save ()
  (unless lean-explorer--saving
    (when (memq lean-explorer-auto-build '(save idle))
      (lean-explorer--build))))

;;; Building

(defun lean-explorer--log-name ()
  (format "*lean-c log: %s*" lean-explorer--module))

(defun lean-explorer--log-buffer ()
  (get-buffer-create (lean-explorer--log-name)))

(defun lean-explorer--first-error ()
  "The first error line of the last build, if any."
  (when-let* ((log (get-buffer (lean-explorer--log-name))))
    (with-current-buffer log
      (save-excursion
        (goto-char (point-min))
        (when (re-search-forward "^.*[Ee]rror:.*$" nil t)
          (truncate-string-to-width (string-trim (match-string-no-properties 0)) 120 nil nil t))))))

(defun lean-explorer--commands ()
  "The commands that regenerate this buffer's artifact, in order."
  (cons (list lean-explorer-lake-program "build" (concat lean-explorer--module ":c"))
        (when (eq lean-explorer-backend 'asm)
          (list (append (list lean-explorer-leanc-program)
                        lean-explorer-asm-flags
                        (list "-o" lean-explorer--artifact lean-explorer--c-file))))))

(defun lean-explorer--build ()
  "Regenerate this buffer's artifact by running the backend's commands."
  (let ((missing (cl-find-if-not #'executable-find
                                 (mapcar #'car (lean-explorer--commands)))))
    (cond
     ((process-live-p lean-explorer--proc)
      (setq lean-explorer--pending t))
     (missing
      ;; signalling here would abort the rest of `after-save-hook'
      (lean-explorer--set-state 'failed)
      (message "lean-explorer: %s is not on PATH" missing))
     (t
      (when (buffer-modified-p)
        (let ((lean-explorer--saving t))
          (save-buffer)))
      (setq lean-explorer--pending nil)
      (make-directory (file-name-directory lean-explorer--artifact) t)
      (with-current-buffer (lean-explorer--log-buffer)
        (let ((inhibit-read-only t))
          (erase-buffer)))
      (lean-explorer--set-state 'building)
      (lean-explorer--run (current-buffer) (lean-explorer--commands) (lean-explorer--hash))))))

(defun lean-explorer--run (src commands hash)
  "Run COMMANDS one after another for SRC, then report on HASH."
  (if (null commands)
      (lean-explorer--succeed src hash)
    (let* ((cmd (car commands))
           (log (lean-explorer--log-buffer))
           (default-directory lean-explorer--root))
      (with-current-buffer log
        (let ((inhibit-read-only t))
          (goto-char (point-max))
          (insert (format "$ %s\n" (string-join cmd " ")))))
      (setq lean-explorer--proc
            (make-process
             :name "lean-explorer"
             :buffer log
             :noquery t
             :connection-type 'pipe
             :command cmd
             :sentinel
             (lambda (proc _event)
               (unless (process-live-p proc)
                 (when (buffer-live-p src)
                   (with-current-buffer src
                     (setq lean-explorer--proc nil)
                     (if (zerop (process-exit-status proc))
                         (lean-explorer--run src (cdr commands) hash)
                       (lean-explorer--fail)))))))))))

(defun lean-explorer--succeed (src hash)
  (with-current-buffer src
    (setq lean-explorer--built-hash hash)
    (lean-explorer--load-artifact src)
    (lean-explorer--set-state (if (equal hash (lean-explorer--hash)) 'fresh 'stale))
    (lean-explorer--drain-pending)))

(defun lean-explorer--fail ()
  (lean-explorer--set-state 'failed)
  (message "lean-explorer: build failed%s"
           (if-let* ((err (lean-explorer--first-error))) (concat ": " err) ""))
  (lean-explorer--drain-pending))

(defun lean-explorer--drain-pending ()
  (when lean-explorer--pending
    (setq lean-explorer--pending nil)
    (unless (eq lean-explorer--state 'fresh)
      (lean-explorer--build))))

;;; Following point

(defconst lean-explorer--decl-re
  (concat "^\\(?:@\\[[^]]*\\][ \t\n]*\\)?"
          "\\(?:\\(?:private\\|protected\\|noncomputable\\|partial\\|unsafe\\|nonrec\\|scoped\\|local\\|public\\|expose\\) +\\)*"
          "\\(?:def\\|abbrev\\|instance\\|opaque\\|axiom\\|structure\\|inductive\\|class\\|theorem\\|lemma\\)\\_>"
          "[ \t]+\\([^ \t\n:({\\[]+\\)"))

(defun lean-explorer--namespace-at-point ()
  "The namespace components in effect at point."
  (let ((limit (point))
        stack)
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "^\\(namespace\\|end\\)[ \t]+\\([^ \t\n]+\\)" limit t)
        (let ((parts (split-string (match-string-no-properties 2) "\\.")))
          (if (equal (match-string-no-properties 1) "namespace")
              (setq stack (append stack parts))
            ;; `end' also closes sections, which do not affect names
            (when (equal (last stack (length parts)) parts)
              (setq stack (butlast stack (length parts))))))))
    stack))

(defun lean-explorer--declaration-at-point ()
  "Fully qualified name of the declaration point is inside."
  (save-excursion
    (end-of-line)
    (when (re-search-backward lean-explorer--decl-re nil t)
      ;; read the name before scanning namespaces, which clobbers the match data
      (let ((name (match-string-no-properties 1)))
        (unless (member name '("namespace" "end" "section" "where" "by"))
          (string-join (append (lean-explorer--namespace-at-point)
                               (split-string name "\\."))
                       "."))))))

(defun lean-explorer--mangle (component)
  "Escape COMPONENT the way the Lean compiler escapes name parts in C."
  (replace-regexp-in-string
   "[^A-Za-z0-9_]"
   (lambda (c)
     (let ((ch (aref c 0)))
       (if (< ch 128) (format "_x%02x" ch) (format "_u%04x" ch))))
   component t t))

(defun lean-explorer--symbol-position (name)
  "Position of the C symbol generated for the dotted Lean NAME.
Tries the fully qualified name first, then drops leading components, so
that `Grade.max' is not confused with another namespace's `max'."
  (let ((parts (mapcar #'lean-explorer--mangle (split-string name "\\.")))
        pos)
    (while (and (null pos) parts)
      (setq pos (lean-explorer--search-symbol (string-join parts "_"))
            parts (cdr parts)))
    pos))

(defun lean-explorer--search-symbol (mangled)
  "Position in the current buffer of the symbol ending in MANGLED.
Ranks the definition of the plain symbol above a `___boxed' variant, a
declaration, and finally any other mention."
  (let ((re (concat "\\_<\\(?:_init_\\)?l[A-Za-z0-9_]*_" (regexp-quote mangled)
                    "\\(___[A-Za-z0-9]+\\)?\\_>"))
        (best nil)
        (rank 99))
    (save-excursion
      (goto-char (point-min))
      (while (and (> rank 1) (re-search-forward re nil t))
        (let* ((bol (line-beginning-position))
               (r (lean-explorer--rank (match-beginning 1)
                                       (= (match-beginning 0) bol)
                                       (char-after)
                                       (buffer-substring-no-properties bol (line-end-position)))))
          (when (< r rank)
            (setq rank r
                  best bol))))
      best)))

(defun lean-explorer--rank (suffixed at-bol next line)
  "Rank a symbol occurrence, 1 being the definition itself.
SUFFIXED is non-nil for a `___' variant, AT-BOL whether the symbol starts
the LINE, and NEXT the character following it."
  (if (eq lean-explorer-backend 'asm)
      ;; a label sits in column zero; .globl and friends only announce it
      (cond ((and at-bol (eq next ?:) (not suffixed)) 1)
            ((and at-bol (eq next ?:)) 2)
            ((string-match-p "\\`[ \t]*\\." line) 3)
            (t 4))
    (let* ((own (string-match-p "\\`\\(LEAN_EXPORT\\|static\\)" line))
           ;; a definition opens a body or initialises a constant;
           ;; a prototype ends in `;', a use site starts with neither
           (definition (and own (or (and (eq next ?\() (string-suffix-p "{" line))
                                    (string-match-p " = " line)))))
      (cond ((and definition (not suffixed)) 1)
            (definition 2)
            (own 3)
            (t 4)))))

(defun lean-explorer-follow-declaration ()
  "Scroll the C window to the declaration at point."
  (interactive)
  (let* ((name (lean-explorer--declaration-at-point))
         (buf lean-explorer--view)
         (win (and (buffer-live-p buf) (get-buffer-window buf t))))
    (when (and name win)
      (let ((pos (with-current-buffer buf (lean-explorer--symbol-position name))))
        (if (not pos)
            (when (called-interactively-p 'interactive)
              (message "lean-explorer: no C symbol for %s" name))
          (with-selected-window win
            (goto-char pos)
            (recenter 3)
            (when (fboundp 'pulse-momentary-highlight-one-line)
              (pulse-momentary-highlight-one-line pos)))
          (with-current-buffer buf (setq lean-explorer--followed name)))))))

(defun lean-explorer--view-window ()
  "A window showing some explorer buffer, if one is visible."
  (catch 'found
    (dolist (win (window-list-1 nil nil t))
      (when (buffer-local-value 'lean-explorer--source (window-buffer win))
        (throw 'found win)))))

(defun lean-explorer--maybe-switch ()
  "Point a visible explorer window at the Lean buffer that is now current."
  (when (and lean-explorer-follow-buffer
             (not lean-explorer-mode)
             (not lean-explorer--declined)
             (not (minibufferp))
             buffer-file-name
             (string-suffix-p ".lean" buffer-file-name))
    (when-let* ((win (lean-explorer--view-window)))
      (let ((old (buffer-local-value 'lean-explorer--source (window-buffer win))))
        ;; stay on whichever output the window was already showing
        (when (buffer-live-p old)
          (setq-local lean-explorer-backend
                      (buffer-local-value 'lean-explorer-backend old)))
        (lean-explorer-mode 1)
        (if (not lean-explorer-mode)
            ;; remember the failure, or the idle timer would retry it forever
            (setq lean-explorer--declined t)
          ;; reuse the window, so a dedicated side window does not blink away
          (let ((dedicated (window-dedicated-p win)))
            (set-window-dedicated-p win nil)
            (set-window-buffer win lean-explorer--view)
            (set-window-dedicated-p win dedicated))
          (when (and (buffer-live-p old) (not (eq old (current-buffer))))
            (with-current-buffer old (lean-explorer-mode -1))))))))

(defun lean-explorer--idle-tick ()
  (lean-explorer--maybe-switch)
  (lean-explorer--maybe-follow))

(defun lean-explorer--maybe-follow ()
  (when (and lean-explorer-follow-point
             (bound-and-true-p lean-explorer-mode)
             (buffer-live-p lean-explorer--view)
             (get-buffer-window lean-explorer--view t))
    (let ((name (lean-explorer--declaration-at-point)))
      (when (and name
                 (not (equal name (buffer-local-value 'lean-explorer--followed
                                                      lean-explorer--view))))
        (lean-explorer-follow-declaration)))))

;;; Entry points

(defun lean-explorer-rebuild ()
  "Regenerate the C for the source buffer, saving it first if needed."
  (interactive)
  (with-current-buffer (lean-explorer--source-buffer)
    (lean-explorer--build)))

(defun lean-explorer-set-backend (backend)
  "Show BACKEND, `c' or `asm', in this buffer's explorer."
  (interactive (list (intern (completing-read "Backend: " '("c" "asm") nil t))))
  (with-current-buffer (lean-explorer--source-buffer)
    (unless (eq backend lean-explorer-backend)
      (setq-local lean-explorer-backend backend)
      (lean-explorer--set-paths)
      (setq lean-explorer--built-hash nil)
      (let ((src (current-buffer)))
        (when (buffer-live-p lean-explorer--view)
          (with-current-buffer lean-explorer--view
            (let ((inhibit-read-only t))
              (erase-buffer))
            (rename-buffer (lean-explorer--view-name
                            (buffer-local-value 'lean-explorer--module src) backend)
                           t)
            (lean-explorer--configure-view (current-buffer) src backend))))
      (lean-explorer--adopt-existing)
      (when (memq lean-explorer--state '(stale unknown))
        (lean-explorer--build)))))

(defun lean-explorer-toggle-backend ()
  "Switch this explorer between the generated C and its assembly."
  (interactive)
  (with-current-buffer (lean-explorer--source-buffer)
    (lean-explorer-set-backend (if (eq lean-explorer-backend 'asm) 'c 'asm))))

(defun lean-explorer-show-log ()
  "Show the output of the last lake build."
  (interactive)
  (with-current-buffer (lean-explorer--source-buffer)
    (display-buffer (lean-explorer--log-buffer))))

(defun lean-explorer--source-buffer ()
  (or (and (bound-and-true-p lean-explorer-mode) (current-buffer))
      (and (buffer-live-p lean-explorer--source) lean-explorer--source)
      (user-error "Not a lean-explorer buffer")))

(defun lean-explorer--adopt-existing ()
  "Load the C already on disk, trusting it if it is newer than the source."
  (let ((c lean-explorer--artifact)
        (src (buffer-file-name)))
    (cond
     ((not (file-readable-p c))
      (lean-explorer--set-state 'unknown))
     ((and (not (buffer-modified-p))
           (time-less-p (file-attribute-modification-time (file-attributes src))
                        (file-attribute-modification-time (file-attributes c))))
      (setq lean-explorer--built-hash (lean-explorer--hash))
      (lean-explorer--load-artifact (current-buffer))
      (lean-explorer--set-state 'fresh))
     (t
      (lean-explorer--load-artifact (current-buffer))
      (lean-explorer--set-state 'stale)))))

;;;###autoload
(define-minor-mode lean-explorer-mode
  "Keep a buffer of Lean's generated C in sync with this source file."
  :lighter (:eval (lean-explorer--lighter))
  (if lean-explorer-mode
      (pcase (and buffer-file-name (lean-explorer--resolve buffer-file-name))
        (`(,root ,module ,_)
         (setq lean-explorer--root root
               lean-explorer--module module)
         (lean-explorer--set-paths)
         (add-hook 'after-save-hook #'lean-explorer--after-save nil t)
         (add-hook 'after-change-functions #'lean-explorer--after-change nil t)
         (add-hook 'kill-buffer-hook #'lean-explorer--cleanup nil t)
         (lean-explorer--ensure-view)
         (lean-explorer--adopt-existing)
         (when (and lean-explorer-build-on-open
                    (memq lean-explorer--state '(stale unknown)))
           (lean-explorer--build))
         (unless (timerp lean-explorer--follow-timer)
           (setq lean-explorer--follow-timer
                 (run-with-idle-timer lean-explorer-follow-delay t
                                      #'lean-explorer--idle-tick))))
        ;; a plain message keeps this usable from a mode hook
        (_ (setq lean-explorer-mode nil)
           (message "lean-explorer: %s is not inside a lake package"
                    (if buffer-file-name
                        (file-name-nondirectory buffer-file-name)
                      "this buffer"))))
    (lean-explorer--cleanup)))

(defun lean-explorer--cleanup ()
  (remove-hook 'after-save-hook #'lean-explorer--after-save t)
  (remove-hook 'after-change-functions #'lean-explorer--after-change t)
  (remove-hook 'kill-buffer-hook #'lean-explorer--cleanup t)
  (when (timerp lean-explorer--timer)
    (cancel-timer lean-explorer--timer))
  (when (process-live-p lean-explorer--proc)
    ;; its sentinel would otherwise finish the build we are tearing down
    (set-process-sentinel lean-explorer--proc #'ignore)
    (delete-process lean-explorer--proc))
  (when-let* ((log (get-buffer (lean-explorer--log-name))))
    (kill-buffer log))
  (when (buffer-live-p lean-explorer--view)
    (kill-buffer lean-explorer--view))
  (setq lean-explorer--view nil
        lean-explorer--proc nil
        lean-explorer--pending nil
        lean-explorer--timer nil
        lean-explorer--built-hash nil
        lean-explorer--state 'unknown)
  (lean-explorer--stop-follow-timer-maybe))

(defun lean-explorer--stop-follow-timer-maybe ()
  "Cancel the shared follow timer once no buffer uses the mode."
  (when (and (timerp lean-explorer--follow-timer)
             ;; the buffer being killed still counts as live and still has the
             ;; mode on, so it must not keep the timer alive
             (not (cl-some (lambda (b)
                             (and (not (eq b (current-buffer)))
                                  (buffer-local-value 'lean-explorer-mode b)))
                           (buffer-list))))
    (cancel-timer lean-explorer--follow-timer)
    (setq lean-explorer--follow-timer nil)))

;;;###autoload
(defun lean-explorer ()
  "Open the generated C of this Lean buffer in a side window, or close it."
  (interactive)
  (cond
   ((bound-and-true-p lean-explorer--source)
    (quit-window))
   ((not (and buffer-file-name (string-suffix-p ".lean" buffer-file-name)))
    (user-error "lean-explorer: not visiting a .lean file"))
   ((and lean-explorer-mode (buffer-live-p lean-explorer--view)
         (get-buffer-window lean-explorer--view t))
    (lean-explorer-mode -1))
   (t
    (unless lean-explorer-mode (lean-explorer-mode 1))
    (when lean-explorer-mode
      (display-buffer (lean-explorer--ensure-view) lean-explorer-display-action)
      (lean-explorer--maybe-follow)))))

(provide 'lean-explorer)
;;; lean-explorer.el ends here
